// templates/chota-vue-pinia/src/ui/molecules/FilterGroup/FilterGroup.component.vue
<template>
  <div class="grouped" role="group">
    <template v-for="filterItem in filterItems" v-bind:key="filterItem.id">
      <Link :isActive="filterItem.selected" @onClick="() => $emit('onFilterClick', filterItem.id)">
      {{ filterItem.label }}
      </Link>
    </template>
  </div>
</template>
<script>
import { defineComponent } from 'vue'
import Link from '../../atoms/Link/Link.component.vue';

export default defineComponent({
  components: { Link },
  props: ['filterItems', 'onFilterClick'],
})
</script>

// templates/chota-react-rtk/src/ui/molecules/FilterGroup/FilterGroup.component.js

import Link from "../../atoms/Link/Link.component";

const FilterGroup = ({ filterItems, onFilterClick }) => (
  <div className="grouped" role="group">
    {filterItems.map((filterItem) => (
      <Link key={filterItem.id} isActive={filterItem.selected} onClick={() => onFilterClick(filterItem.id)}>{filterItem.label}</Link>
    ))}
  </div>
);

export default FilterGroup;
