// templates/chota-react-zustand/src/containers/ConfigContainer.js
import { useEffect } from "react";
import useStore from "../state";
export default function ConfigContainer() {
  const theme = useStore((state) => state.config.theme);
  useEffect(() => {
    const bodyClass = document.body.classList;
    theme === 'dark'
      ? bodyClass.add("dark")
      : bodyClass.remove("dark");
  }, [theme]);
  return null;
}

// templates/chota-vue-pinia/src/containers/ConfigContainer.vue
<template>
</template>

<script>
import { defineComponent } from 'vue';
import { useConfigStore } from '../state/config';

export default defineComponent({
  props: [],
  setup() {
    const configData = useConfigStore();
    return {
      configData,
      theme: configData.theme,
    }
  },
  watch: {
    'configData.config.theme': {
      handler(newVal, oldVal) {
        const bodyClass = document.body.classList;
        if (newVal !== oldVal) {
          if (newVal === 'dark') {
            bodyClass.add("dark");
          } else {
            bodyClass.remove("dark");
          }
        }
      },
      deep: true
    }
  }
})
</script>
