// templates/chota-angular-ngrx/src/ui/atoms/Button/Button.component.ts
import { Component, Input, Output, EventEmitter, HostBinding } from '@angular/core';

@Component({
  selector: 'app-button',
  templateUrl: './Button.component.html',
  styleUrls: ['./Button.style.css'],
})
export default class ButtonComponent {

  @Input()
  isLoading?: boolean = false;

  @Input()
  classes?: string;

  @HostBinding("attr.type")
  externalType = "";

  @Input()
  set type(value: string) {
    this._Type = value;
    this.externalType = null;
  }

  get type() {
    return this._Type;
  }

  private _Type = "";

  get computedClasses() {
    return this.isLoading ? `${this.classes} loading-button` : this.classes;
  }

  /**
   * Optional click handler
   */
  @Output()
  onClick = new EventEmitter<Event>();
}

<ng-template [ngIf]="isLoading" [ngIfElse]="normal">
  <button [ngClass]="computedClasses" [disabled]="isLoading">
    <app-loader width="2px" size="1.2rem" color="#fff"></app-loader>
  </button>
</ng-template>
<ng-template #normal>
  <button type="button" (click)="onClick.emit($event)" [ngClass]="computedClasses">
    <ng-content></ng-content>
  </button>
</ng-template>

// templates/chota-wc-saga/src/ui/atoms/Button/Button.component.js
import { html } from "lit";
import style from './Button.style';
import "../Loader/app-loader";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import emit from "../../../utils/events/emit";

export default function Button(props) {
  useComputedStyles(this, [style]);
  if (props.isLoading) {
    return html`
      <button type="button" class=${`${props.classes} loading-button`}>
        <app-loader .width=${'2px'} .size=${'1.2rem'} .color=${'#fff'}>Loading...</app-loader>
      </button>
    `;
  }
  return html`<button type="button"
      class="${props.classes}"
      @click="${() => emit(this, "onClick", props)}"><slot></slot></button>`;
}
