// templates/chota-vue-pinia/src/ui/atoms/Button/Button.component.vue
<template>
    <button  v-if="isLoading" :disabled="disabled" @click="$emit('onClick')" :class="getButtonClass()">
      <Loader width="2px" size="1.2rem" color="#fff" />
    </button>
    <button  v-else :disabled="disabled" :type="type" @click="$emit('onClick')" :class="getButtonClass()"><slot /></button>
</template>
<script>
import { defineComponent } from 'vue'
import Loader from '../Loader/Loader.component.vue';

export default defineComponent({
  components: {
    Loader
  },
  props: ['isLoading', 'class', 'disabled', 'onClick', 'label', 'type'],
  methods: {
    getButtonClass() {
      return `${this.class} loading-button`;
    }
  },
})
</script>

<style scoped src="./Button.style.css"></style>

// templates/chota-wc-saga/src/ui/atoms/Button/Button.component.js
import { html } from "lit";
import style from './Button.style';
import "../Loader/app-loader";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import emit from "../../../utils/events/emit";

export default function Button(props) {
  useComputedStyles(this, [style]);
  if (props.isLoading) {
    return html`
      <button type="button" class=${`${props.classes} loading-button`}>
        <app-loader .width=${'2px'} .size=${'1.2rem'} .color=${'#fff'}>Loading...</app-loader>
      </button>
    `;
  }
  return html`<button type="button"
      class="${props.classes}"
      @click="${() => emit(this, "onClick", props)}"><slot></slot></button>`;
}
