// templates/chota-vue-pinia/src/ui/atoms/Button/Button.component.vue
<template>
    <button  v-if="isLoading" :disabled="disabled" @click="$emit('onClick')" :class="getButtonClass()">
      <Loader width="2px" size="1.2rem" color="#fff" />
    </button>
    <button  v-else :disabled="disabled" :type="type" @click="$emit('onClick')" :class="getButtonClass()"><slot /></button>
</template>
<script>
import { defineComponent } from 'vue'
import Loader from '../Loader/Loader.component.vue';

export default defineComponent({
  components: {
    Loader
  },
  props: ['isLoading', 'class', 'disabled', 'onClick', 'label', 'type'],
  methods: {
    getButtonClass() {
      return `${this.class} loading-button`;
    }
  },
})
</script>

<style scoped src="./Button.style.css"></style>

// templates/chota-react-zustand/src/ui/atoms/Button/Button.component.jsx
import Loader from "../Loader/Loader.component";

import './Button.style.css';

export default function Button(props) {
  const transformedProps = { ...props };
  delete transformedProps.isLoading;
  if (props.isLoading) {
    return (
      <button {...transformedProps} disabled={props.isLoading} className={`${props.className} loading-button`}>
        <Loader width="2px" size="1.2rem" color="#fff" />
      </button>
    );
  }
  return <button {...transformedProps}>{props.children}</button>;
}
