// templates/chota-react-redux/src/ui/atoms/Link/Link.component.js
/* eslint-disable jsx-a11y/anchor-is-valid */
import { propTypes } from "./Link.type";



const Link = ({ isActive, children, onClick }) => (
  <a
    href="#"
    className={`button ${isActive ? "primary" : "outline"}`}
    onClick={onClick}
    disabled={isActive}
    role="button"
  >
    {children}
  </a>
);

Link.propTypes = propTypes

export default Link;

// templates/chota-wc-saga/src/ui/atoms/Link/Link.component.js
import { html } from "lit";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import style from './Link.style';
import emit from "../../../utils/events/emit";

 export default function Link({ isActive, onClick }) {
  useComputedStyles(this, [style]);
  return html`
    <a
      href="#"
      class=${`button ${isActive ? "primary" : "outline"}`}
      @click=${() => emit(this, "onClick", onClick)}
      .disabled=${isActive}
      role="button"
    >
      <slot></slot>
    </a>
  `;
}
