// templates/chota-vue-pinia/src/ui/atoms/Link/Link.component.vue
<template>
  <a href="#" :class="getLinkClass()" :disabled="isActive" role="button" @click="handleClick">
    <slot />
  </a>
</template>
<script>
import { defineComponent } from 'vue'

export default defineComponent({
  props: ['isActive', 'class', 'onClick'],
  methods: {
    getLinkClass() {
      return `button ${this.isActive ? "primary" : "outline"}`;
    },
    handleClick(e) {
      e.preventDefault();
      console.log('asdasd');
      this.$emit('onClick');
    },
  },
})
</script>

<style scoped src="./Link.style.css"></style>

// templates/chota-wc-saga/src/ui/atoms/Link/Link.component.js
import { html } from "lit";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import style from './Link.style';
import emit from "../../../utils/events/emit";

 export default function Link({ isActive, onClick }) {
  useComputedStyles(this, [style]);
  return html`
    <a
      href="#"
      class=${`button ${isActive ? "primary" : "outline"}`}
      @click=${() => emit(this, "onClick", onClick)}
      .disabled=${isActive}
      role="button"
    >
      <slot></slot>
    </a>
  `;
}
