// templates/chota-vue-pinia/src/ui/organisms/SiteHeader/SiteHeader.component.vue
<template>
  <header class="header">
    <div class="header-block">
      <div>
        <h1>{{ headerData.brandName }}</h1>
      </div>
      <div>
        <h1 role="button" @click="() => updateTheme()" className="text-right pointer">
          {{ headerData.theme === "dark" ? "☀️" : "🌙" }}
        </h1>
      </div>
    </div>
  </header>
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
  props: ['headerData', 'events'],
  methods: {
    updateTheme() {
      this.events.onThemeChangeClick();
      this.$theme = this.headerData.theme === "dark" ? "dark" : "light";
    }
  }
})
</script>

<style scoped src="./SiteHeader.style.css"></style>

// templates/chota-react-redux/src/ui/organisms/SiteHeader/SiteHeader.component.js
import './SiteHeader.style.css';

export default function SiteHeader({ headerData, events }) {
  const { brandName, theme } = headerData;
  const { onThemeChangeClick } = events;
  return (
    <header className="header">
      <div className="header-block">
        <div>
          <h1>{brandName}</h1>
        </div>
        <div>
          <h1 role="button" onClick={() => onThemeChangeClick()} className="text-right pointer">{theme === "dark" ? "☀️" : "🌙"}</h1>
        </div>
      </div>
    </header>
  );
}
