// templates/chota-angular-ngrx/src/ui/molecules/TodoItems/TodoItems.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import TodoItemComponent from '../../atoms/TodoItem/TodoItem.component';

@Component({
  selector: 'app-todo-items',
  standalone: true,
  imports: [TodoItemComponent],
  templateUrl: './TodoItems.component.html',
  styleUrls: ['./TodoItems.style.css'],
})
export default class TodoItemsComponent {
  @Input() todos: any[] = [];
  @Input() isDisabled = false;

  @Output() onToggleClick = new EventEmitter<any>();
  @Output() onEditClick = new EventEmitter<any>();
  @Output() onDeleteClick = new EventEmitter<any>();
}


<ng-template [ngIf]="todos && todos.length" [ngIfElse]="empty">
  <ul class="todo-items">
      <app-todo-item
        *ngFor="let todo of todos"
        [id]="todo.id"
        [text]="todo.text"
        [completed]="todo.completed"
        isDisabled="isDisabled"
        (onToggleClick)="onToggleClick.emit(todo)"
        (onEditClick)="onEditClick.emit(todo)"
        (onDeleteClick)="onDeleteClick.emit(todo.id)"
      >
      </app-todo-item>
  </ul>
</ng-template>
<ng-template #empty>
  <p class="text-center empty-text">Nothing to display here. Carry on.</p>
</ng-template>

// templates/chota-wc-saga/src/ui/molecules/TodoItems/TodoItems.component.js
import { html } from "lit";
import style from "./TodoItems.style";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import emit from "../../../utils/events/emit";
import "../../atoms/TodoItem/app-todo-item";

function TodoItems({ todos, isDisabled }) {
  useComputedStyles(this, [style]);

  return todos && todos.length ? html`
    <ul class="todo-items">
      ${todos.map((todo) => html`
        <app-todo-item
          .key=${todo.id}
          .id=${todo.id}
          .text=${todo.text}
          .completed =${todo.completed}
          .isDisabled=${isDisabled}
          @onToggleClick=${() => emit(this, "onToggleClick", todo)}
          @onEditClick=${() => emit(this, "onEditClick", todo)}
          @onDeleteClick=${() => emit(this, "onDeleteClick", todo.id)}
        ></app-todo-item>
      `)}
    </ul>
  ` : html`
    <p class="text-center empty-text">Nothing to display here. Carry on.</p>
  `;
};

export default TodoItems;
