// templates/chota-angular-ngrx/src/ui/molecules/AddTodoForm/AddTodoForm.component.ts
import { Component, Input, Output, EventEmitter } from "@angular/core";

@Component({
  selector: "app-add-todo-form",
  templateUrl: "./AddTodoForm.component.html",
  styleUrls: ["./AddTodoForm.style.css"],
})
export default class AddTodoFormComponent {
  /**
   * Is this the principal call to action on the page?
   */
  @Input()
  buttonInfo = {
    variant: "primary",
    label: "Add",
  };

  @Input()
  placeholder = "Add your task";

  @Input()
  isLoading = false;

  @Input()
  todoValue?: string;

  /**
   * Optional click handler
   */
  @Output()
  onTodoAdd = new EventEmitter();

  @Output()
  onTodoUpdate = new EventEmitter();

  inputValue: String;

  get buttonClasses() {
    return `button ${this.buttonInfo.variant}`;
  }

  onSubmit(e) {
    e.preventDefault();
    if (!this.inputValue.trim()) {
      return;
    }
    if (this.todoValue) {
      this.onTodoUpdate.emit(this.inputValue);
    } else {
      this.onTodoAdd.emit(this.inputValue);
    }
    this.inputValue = "";
  }

  handleChange(e) {
    this.todoValue = e;
  }
}

<div>
  <form
    (onSubmit)="onSubmit"
    class="add-todo-form"
  >
    <div class="grouped">
      <app-input [value]="inputValue" [disabled]="isLoading" [placeholder]="placeholder" (onChange)="handleChange" ></app-input>
      <app-button [classes]="buttonClasses" [isLoading]="isLoading" type="submit">
        {{buttonInfo.label}}
      </app-button>
    </div>
  </form>
</div>

// templates/chota-react-zustand/src/ui/molecules/AddTodoForm/AddTodoForm.component.jsx
import React, { useEffect, useState } from "react";
import Input from "../../atoms/Input/Input.component";
import Button from "../../atoms/Button/Button.component";

const AddTodoForm = ({
  buttonInfo = { label: 'Add', variant: 'primary' },
  placeholder,
  isLoading,
  onTodoAdd,
  onTodoUpdate,
  todoValue,
}) => {
  const [inputValue, setInputValue] = useState(todoValue || '');
  const { label, variant } = buttonInfo;

  const handleChange = (e) => {
    const { value } = e.target;
    setInputValue(value);
  };

  useEffect(() => setInputValue(todoValue), [todoValue]);

  return (
    <div>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          if (!inputValue.trim()) {
            return;
          }
          if(todoValue) {
            onTodoUpdate(inputValue);
          } else {
            onTodoAdd(inputValue);
          }
          setInputValue('');
        }}
      >
        <div className="grouped">
          <Input className="" value={inputValue} disabled={isLoading} placeholder={placeholder} onChange={handleChange} />
          <Button className={`button ${variant}`} isLoading={isLoading} type="submit">
            {label}
          </Button>
        </div>
      </form>
    </div>
  );
};

export default AddTodoForm;
