// templates/chota-vue-pinia/src/ui/atoms/Loader/Loader.component.vue
<template>
  <span class="loader" :style="getLoaderStyle()"></span>
</template>

<script>
import { defineComponent } from "vue";

export default defineComponent({
  props: ['size', 'width', 'color'],
  methods: {
    getLoaderStyle() {
      return `
      height: ${this.size || '48px'};
        width: ${this.size || '48px'};
        border: ${this.width || '5px'} solid ${this.color || '#fff'};
        border-bottom-color: transparent;
      `;
    }
  },
})
</script>

<style scoped src="./Loader.style.css">

</style>

// templates/chota-react-zustand/src/ui/atoms/Loader/Loader.component.jsx
import "./Loader.style.css";

export default function Loader({ size, width, color }) {
  return (
    <span
      className="loader"
      style={{
        height: size || "48px",
        width: size || "48px",
        border: `${width || "5px"} solid ${color || "#fff"}`,
        borderBottomColor: "transparent",
      }}
    ></span>
  );
}
