// templates/chota-wc-saga/src/ui/atoms/Link/Link.component.js
import { html } from "lit";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import style from './Link.style';
import emit from "../../../utils/events/emit";

 export default function Link({ isActive, onClick }) {
  useComputedStyles(this, [style]);
  return html`
    <a
      href="#"
      class=${`button ${isActive ? "primary" : "outline"}`}
      @click=${() => emit(this, "onClick", onClick)}
      .disabled=${isActive}
      role="button"
    >
      <slot></slot>
    </a>
  `;
}

// templates/chota-angular-ngrx/src/ui/atoms/Link/Link.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-link',
  standalone: true,
  templateUrl: './Link.component.html',
  styleUrls: ['./Link.style.css'],
})
export default class LinkComponent {
  @Input() isActive = false;

  get classes() {
    return `button ${this.isActive ? 'primary' : 'outline'}`;
  }

  @Output() onClick = new EventEmitter<Event>();
}


<a
  href="#"
  type="button"
  (click)="onClick.emit($event)"
  [class]="classes"
  [attr.disabled]="isActive"
  role="button"
>
  <ng-content></ng-content>
</a>
