// templates/chota-wc-saga/src/ui/molecules/FilterGroup/FilterGroup.component.js
import { css, html } from "lit";
import emit from "../../../utils/events/emit";
import "../../atoms/Link/app-link";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import style from './FilterGroup.style';

function FilterGroup({ filterItems }) {
  useComputedStyles(this, [style]);
  return html`
  <div class="grouped" role="group">
    ${filterItems.map((filterItem) => html`
      <app-link key=${filterItem.id} .isActive=${filterItem.selected} @onClick=${() => emit(this, "onFilterClick", filterItem.id)}>${filterItem.label}</app-link>
    `)}
  </div>
`;
}

export default FilterGroup;

// templates/chota-angular-ngrx/src/ui/molecules/FilterGroup/FilterGroup.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import LinkComponent from '../../atoms/Link/Link.component';

@Component({
  selector: 'app-filter-group',
  standalone: true,
  imports: [LinkComponent],
  templateUrl: './FilterGroup.component.html',
  styleUrls: ['./FilterGroup.style.css'],
})
export default class FilterGroupComponent {
  @Input() filterItems: { id: string; label: string; selected: boolean }[] = [];
  @Output() onFilterClick = new EventEmitter<string>();
}


<div class="grouped" role="group">
  @for (filterItem of filterItems; track filterItem.id) {
    <app-link
      [isActive]="filterItem.selected"
      (onClick)="onFilterClick.emit(filterItem.id)"
    >
      {{ filterItem.label }}
    </app-link>
  }
</div>
