// templates/chota-react-redux/src/ui/organisms/SiteHeader/SiteHeader.component.js
import './SiteHeader.style.css';

export default function SiteHeader({ headerData, events }) {
  const { brandName, theme } = headerData;
  const { onThemeChangeClick } = events;
  return (
    <header className="header">
      <div className="header-block">
        <div>
          <h1>{brandName}</h1>
        </div>
        <div>
          <h1 role="button" onClick={() => onThemeChangeClick()} className="text-right pointer">{theme === "dark" ? "☀️" : "🌙"}</h1>
        </div>
      </div>
    </header>
  );
}

// templates/chota-angular-ngrx/src/ui/organisms/SiteHeader/SiteHeader.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-site-header',
  standalone: true,
  templateUrl: './SiteHeader.component.html',
  styleUrls: ['./SiteHeader.style.css'],
})
export default class SiteHeaderComponent {
  @Input() headerData: { brandName: string; theme: string } = {
    brandName: 'Todo App',
    theme: 'light',
  };

  @Input() events: { onThemeChangeClick: () => void } = {
    onThemeChangeClick: () => {},
  };
}


<div class="header">
  <div class="header-block">
    <div>
      <h1>{{ headerData.brandName }}</h1>
    </div>
    <div>
      <h1
        role="button"
        (click)="events.onThemeChangeClick()"
        class="text-right pointer"
      >
        {{ headerData.theme === 'dark' ? '\u2600\uFE0F' : '\uD83C\uDF19' }}
      </h1>
    </div>
  </div>
</div>
