// templates/chota-wc-saga/src/ui/organisms/TodoFilters/TodoFilters.component.js
import { css, html } from "lit";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import "../../molecules/FilterGroup/app-filter-group";
import "../../skeletons/Skeleton/app-skeleton";

export default function TodoFilters({ filtersData, events }) {
  useComputedStyles(this, [css``]);
  const {
    onTodoFilterUpdate,
  } = events;
  return filtersData.isContentLoading ? html`
    <div style=${`display: flex; gap: 1rem;`}>
      <app-skeleton height="24px" ></app-skeleton>
      <app-skeleton height="24px" ></app-skeleton>
      <app-skeleton height="24px" ></app-skeleton>
    </div>
    ` : html`
      <app-filter-group
        .filterItems=${filtersData}
        @onFilterClick=${onTodoFilterUpdate}
      ></app-filter-group>
    `
}

// templates/chota-vue-pinia/src/ui/organisms/TodoFilters/TodoFilters.component.vue
<template>
    <div>
        <div v-if="filtersData && filtersData.isContentLoading" style="display:flex; gap: 1rem;">
          <Skeleton height="24px" />
          <Skeleton height="24px" />
          <Skeleton height="24px" />
        </div>
        <template v-else>
          <FilterGroup
            :filterItems="filtersData"
            @onFilterClick="events.onTodoFilterUpdate"
          />
        </template>
    </div>
  </template>
  <script>
  import { defineComponent } from 'vue';
  import FilterGroup from '../../molecules/FilterGroup/FilterGroup.component.vue';
  import Skeleton from '../../skeletons/Skeleton/Skeleton.component.vue';
  
  export default defineComponent({
    components: { FilterGroup, Skeleton },
    props: ['filtersData', 'events'],
  })
  </script>
