// templates/chota-react-zustand/src/ui/atoms/Loader/Loader.component.jsx
import "./Loader.style.css";

export default function Loader({ size, width, color }) {
  return (
    <span
      className="loader"
      style={{
        height: size || "48px",
        width: size || "48px",
        border: `${width || "5px"} solid ${color || "#fff"}`,
        borderBottomColor: "transparent",
      }}
    ></span>
  );
}

// templates/chota-angular-ngrx/src/ui/atoms/Loader/Loader.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-loader',
  templateUrl: './Loader.component.html',
  styleUrls: ['./Loader.style.css'],
})
export default class LoaderComponent {
  @Input()
  size = '48px';
  @Input()
  width = '5px';
  
  @Input()
  color = '#fff';

  get styles() {
    return `
    height: ${this.size};
    width:  ${this.size};
    border: ${this.width} solid ${this.color};
    border-bottom-color: transparent;
    `;
  }
}

<span
  class="loader"
  [attr.style]="styles"
></span>
