// templates/chota-wc-saga/src/ui/atoms/TodoItem/TodoItem.component.js
import { html } from "lit";
import style from "./TodoItem.style";

import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import emit from "../../../utils/events/emit";

import "../Input/app-input";
import "../IconButton/app-icon-button";

function TodoItem({
  onToggleClick,
  completed,
  text,
  id,
  onEditClick,
  onDeleteClick,
}) { 
  useComputedStyles(this, [style]);
  return html`
  <li
    style=${
      `text-decoration: ${completed ? "line-through" : "none"};`
    }
    class="todo-item"
  >
    <label htmlFor=${`checkbox${id}`}>
      <app-input
        id=${`checkbox${id}`}
        @onInput=${(e) => emit(this, "onToggleClick", e)}
        name="checkbox"
        .type=${`checkbox`}
        @onChange=${(e) => e.target.value}
        .checked=${completed}
      ></app-input>
        ${text}
      <span class="icon-buttons">
        <app-icon-button
          .variant=${`clear`}
          .alt=${`edit`}
          .iconName=${`edit`}
          .size=${`16`}
          @onClick=${(e) => emit(this, "onEditClick", e)}
        ></app-icon-button>
        <app-icon-button
          .variant=${`clear`}
          .alt=${`edit`}
          .iconName=${`trash-2`}
          .size=${`16`}
          @onClick=${(e) => emit(this, "onDeleteClick", e)}
        ></app-icon-button>
      </span>
    </label>
  </li>
  `;
}

export default TodoItem;

// templates/chota-vue-pinia/src/ui/atoms/TodoItem/TodoItem.component.vue
<template>
  <li
    :style="getTodoItemStyle()"
    class="todo-item"
  >
    <label :htmlFor="getInputId()">
      <Input
        :id="getInputId()"
        name="checkbox"
        type="checkbox"
        :checked="completed"
        @onInput="$emit('onToggleClick')"
      />
      {{text}}
      <span class="icon-buttons">
        <IconButton
          variant="clear"
          alt="edit"
          iconName="edit"
          size="16"
          @onClick="$emit('onEditClick')"
        />
        <IconButton
          variant="clear"
          alt="remove"
          iconName="trash-2"
          size="16"
          @onClick="$emit('onDeleteClick')"
        />
      </span>
    </label>
  </li>
</template>
<script>
import { defineComponent } from 'vue'
import Input from '../Input/Input.component.vue';
import IconButton from '../IconButton/IconButton.component.vue';

export default defineComponent({
  components: { Input, IconButton },
  props: [
    'onToggleClick',
    'completed',
    'text',
    'id',
    'onEditClick',
    'onDeleteClick',
  ],
  methods: {
    getInputId() {
      return `checkbox${this.id}`;
    },
    getTodoItemStyle() {
      return `text-decoration: ${this.completed ? "line-through" : "none"}`;
    },
  },
})
</script>

<style scoped src="./TodoItem.style.css"></style>
