// templates/chota-wc-saga/src/ui/skeletons/Skeleton/Skeleton.component.js
import { html } from "lit";
import styles from "./Skeleton.style";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";

export default function Skeleton({ variant, height, width, styleCSS }) {
  useComputedStyles(this, [styles]);
  return html`
    <div
      class=${`skeleton skeleton-${variant ? variant : "text"}`}
      style=${`
        ${styleCSS || ''}
        height: ${height};
        width: ${width};
      `}
    ></div>
  `;
}

// templates/chota-angular-ngrx/src/ui/skeletons/Skeleton/Skeleton.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-skeleton',
  standalone: true,
  templateUrl: './Skeleton.component.html',
  styleUrls: ['./Skeleton.style.css'],
})
export default class SkeletonComponent {
  @Input()
  width = "100%";

  @Input()
  height = "1rem";

  @Input()
  style = {};

  @Input()
  variant = "text";

  get classes() {
    return `skeleton skeleton-${this.variant}`;
  }

  get styles() {
    return { ...this.style, height: this.height, width: this.width };
  }
}

<div
  [ngStyle]="styles"
  [ngClass]="classes"
></div>
