// templates/chota-wc-saga/src/ui/skeletons/Skeleton/Skeleton.component.js
import { html } from "lit";
import style from "./Skeleton.style";

export default function Skeleton({ variant, height, width, style }) {
  useComputedStyles(this, [style]);
  return html`
    <div
      class=${`skeleton skeleton-${variant ? variant : "text"}`}
      style=${`
        ${style}
        height: ${height};
        width: ${width};
      `}
    ></div>
  `;
}

// templates/chota-vue-pinia/src/ui/skeletons/Skeleton/Skeleton.component.vue
<template>
  <div :class="getSkeletonClass()" :style="getSkeletonStyle()"></div>
</template>
<script>
import { defineComponent } from 'vue'

export default defineComponent({
  props: ['variant', 'height', 'width', 'style'],
  methods: {
    getSkeletonStyle() {
      return `
      height: ${this.height};
      width: ${this.width};
      `;
    },
    getSkeletonClass() {
      return `skeleton skeleton-${this.variant ? this.variant : 'text'}`;
    }
  }
})
</script>

<style scoped src="./Skeleton.style.css"></style>
