// templates/chota-wc-saga/src/ui/organisms/TodoFilters/TodoFilters.component.js
import { css, html } from "lit";
import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import "../../molecules/FilterGroup/app-filter-group";
import "../../skeletons/Skeleton/app-skeleton";

export default function TodoFilters({ filtersData, events }) {
  useComputedStyles(this, [css``]);
  const {
    onTodoFilterUpdate,
  } = events;
  return filtersData.isContentLoading ? html`
    <div style=${`display: flex; gap: 1rem;`}>
      <app-skeleton height="24px" ></app-skeleton>
      <app-skeleton height="24px" ></app-skeleton>
      <app-skeleton height="24px" ></app-skeleton>
    </div>
    ` : html`
      <app-filter-group
        .filterItems=${filtersData}
        @onFilterClick=${onTodoFilterUpdate}
      ></app-filter-group>
    `
}

// templates/chota-angular-ngrx/src/ui/organisms/TodoFilters/TodoFilters.component.ts
import { Component, Input } from '@angular/core';
import FilterGroupComponent from '../../molecules/FilterGroup/FilterGroup.component';

@Component({
  selector: 'app-todo-filters',
  standalone: true,
  imports: [FilterGroupComponent],
  templateUrl: './TodoFilters.component.html',
  styleUrls: ['./TodoFilters.style.css'],
})
export default class TodoFiltersComponent {
  @Input() filtersData: { id: string; label: string; selected: boolean }[] = [];

  @Input() events: { onTodoFilterUpdate: (id: string) => void } = {
    onTodoFilterUpdate: () => {},
  };
}


<ng-template [ngIf]="filtersData.isContentLoading" [ngIfElse]="normal">
  <div class="filter-loading">
    <app-skeleton height="24px"></app-skeleton>
    <app-skeleton height="24px"></app-skeleton>
    <app-skeleton height="24px"></app-skeleton>
  </div>
</ng-template>
<ng-template #normal>
  <app-filter-group
    [filterItems]="filtersData"
    (onFilterClick)="events.onTodoFilterUpdate()"
  ></app-filter-group>
</ng-template>
