// templates/chota-angular-ngrx/src/ui/atoms/Alert/Alert.component.ts
import { Component, Input, Output, EventEmitter, OnChanges, SimpleChanges } from '@angular/core';
import ImageComponent from '../Image/Image.component';
import IconButtonComponent from '../IconButton/IconButton.component';

@Component({
  selector: 'app-alert',
  standalone: true,
  imports: [ImageComponent, IconButtonComponent],
  templateUrl: './Alert.component.html',
  styleUrls: ['./Alert.style.css'],
})
export default class AlertComponent implements OnChanges {
  @Input() show = false;
  showAlert = false;

  @Input() variant?: string;

  get classes() {
    return `bg-${this.variant === 'error' ? 'error' : 'primary'} text-white alert`;
  }

  get src() {
    return `https://icongr.am/feather/${
      this.variant === 'error' ? 'alert-triangle' : 'info'
    }.svg?size=24&color=ffffff`;
  }

  @Input() message = 'Alert';

  @Output() onCloseClick = new EventEmitter<Event>();

  ngOnChanges(changes: SimpleChanges) {
    if (changes['show']) {
      this.showAlert = changes['show'].currentValue;
    }
  }

  handleClose(e: Event) {
    this.showAlert = false;
    this.onCloseClick.emit(e);
  }
}


@if (showAlert) {
  <div [class]="classes">
    <div class="message">
      <app-image [src]="src"></app-image>
      <span>{{ message }}</span>
    </div>
    <div>
      <app-icon-button
        variant="clear"
        alt="close"
        color="ffffff"
        iconName="x"
        size="16"
        (onClick)="handleClose($event)"
      ></app-icon-button>
    </div>
  </div>
}

// templates/chota-vue-pinia/src/ui/atoms/Alert/Alert.component.vue
<template>
  <div v-if="showAlert" :class="getVariantClass()">
    <div class="message">
      <Image :src="getImageSrc()" alt="variant" />
      <span>{{ message }}</span>
    </div>
    <div>
      <IconButton variant="clear" alt="close" color="ffffff" iconName="x" size="16" @onClick="handleClose" />
    </div>
  </div>
</template>

<script>
import { defineComponent } from "vue";
import Image from "../Image/Image.component.vue";
import IconButton from "../IconButton/IconButton.component.vue";

export default defineComponent({
  components: { Image, IconButton },
  props: ['show', 'message', 'variant', 'onCloseClick'],
  data() {
    return {
      showAlert: true,
    }
  },
  watch: {
    show(newVal, oldVal) {
      if (newVal !== oldVal) {
        this.showAlert = newVal;
      }
    }
  },
  methods: {
    handleClose(e) {
      this.showAlert = false;
      if (this.onCloseClick) {
        this.onCloseClick(e);
      }
    },
    getImageSrc() {
      return `https://icongr.am/feather/${this.variant === "error" ? "alert-triangle" : "info"}.svg?size=24&color=ffffff`;
    },
    getVariant() {
      return this.variant === 'error' ? 'error' : 'primary';
    },
    getVariantClass() {
      return `bg-${this.getVariant()} text-white alert`;
    }
  }
});
</script>

<style scoped src="./Alert.style.css"></style>
