// templates/chota-wc-saga/src/ui/molecules/TodoItems/TodoItems.component.js
import c"./TodoItems.style.css";

import TodoItem from "../../atoms/TodoItem/TodoItem.component";
import { propTypes } from "./TodoItems.type";

const TodoItems = ({ todos, isDisabled, onToggleClick, onEditClick, onDeleteClick }) => {
  return todos && todos.length ? (
    <ul className="todo-items">
      {todos.map((todo) => (
        <TodoItem
          key={todo.id}
          id={todo.id}
          {...todo}
          isDisabled={isDisabled}
          onToggleClick={() => onToggleClick(todo)}
          onEditClick={() => onEditClick(todo)}
          onDeleteClick={() => onDeleteClick(todo.id)}
        />
      ))}
    </ul>
  ) : (
    <p className="text-center empty-text">Nothing to display here. Carry on.</p>
  );
};

TodoItems.propTypes = propTypes

export default TodoItems;

// templates/chota-vue-pinia/src/ui/molecules/TodoItems/TodoItems.component.vue
<template>
  <div>
    <ul v-if="todos && todos.length" class="todo-items">
      <template v-for="todo in todos" v-bind:key="todo.id" >
        <TodoItem :id="todo.id" :completed="todo.completed" :text="todo.text" @onToggleClick="$emit('onToggleClick', todo)" @onEditClick="$emit('onEditClick', todo)" @onDeleteClick="$emit('onDeleteClick', todo.id)" />
      </template>
    </ul>
    <p v-else class="text-center empty-text">Nothing to display here. Carry on.</p>
  </div>
</template>
<script>
import { defineComponent } from 'vue';
import TodoItem from '../../atoms/TodoItem/TodoItem.component.vue';

export default defineComponent({
  components: { TodoItem },
  props: ['todos', 'isDisabled', 'onToggleClick', 'onEditClick', 'onDeleteClick'],
})
</script>

<style scoped src="./TodoItems.style.css"></style>
