// templates/chota-react-saga/src/containers/TodoListContainer.jsx
import TodoList from "../ui/organisms/TodoList/TodoList.component";
import { useDispatch, useSelector } from "react-redux";
import {
  createTodo,
  deleteTodo,
  editTodo,
  readTodo,
  toggleTodo,
  updateTodo,
} from "../state/todo/todo.actions";
import { getSelectedFilter } from "../state/filters/filters.selectors";
import { getVisibleTodos } from "../state/todo/todo.selectors";
import { useEffect } from "react";

export default function TodoListContainer() {
  const dispatch = useDispatch();
  const selectedFilter = useSelector(getSelectedFilter);
  const todoData = useSelector((state) =>
    getVisibleTodos(state.todo, selectedFilter.id)
  );

  useEffect(() => {
    dispatch(readTodo());
  }, [dispatch])

  /* istanbul ignore next */
  const events = {
    onTodoCreate: (payload) => dispatch(createTodo(payload)),
    onTodoEdit: (payload) => dispatch(editTodo(payload)),
    onTodoUpdate: (text) =>
      dispatch(updateTodo({ id: todoData.currentTodoItem.id, text })),
    onTodoToggleUpdate: (id) => dispatch(toggleTodo(id)),
    onTodoDelete: (payload) => dispatch(deleteTodo(payload)),
  };

  return <TodoList todoData={todoData} events={events} />;
}

// templates/chota-wc-saga/src/containers/TodoListContainer.js
import { LitElement, html } from 'lit-element';
import store, { useDispatch } from '../state';
import { connect } from 'pwa-helpers';

import "../ui/organisms/TodoFilters/app-todo-filters";

import {
  createTodo,
  deleteTodo,
  editTodo,
  readTodo,
  toggleTodo,
  updateTodo,
} from "../state/todo/todo.actions";

import { getSelectedFilter } from "../state/filters/filters.selectors";
import { getVisibleTodos } from "../state/todo/todo.selectors";

import "../ui/organisms/TodoList/app-todo-list";

export default class TodoListContainer extends connect(store)(LitElement) {
  static get properties() {
    return {
      todoData: { type: Object },
      selectedFilter: { type: Object },
      events: { type: Object }
    };
  }
  constructor() {
    super();
    const dispatch = useDispatch();
    this.events = {
      onTodoCreate: (e) => dispatch(createTodo(e.detail)),
      onTodoEdit: (e) => dispatch(editTodo(e.detail)),
      onTodoUpdate: (e) =>
        dispatch(updateTodo({ id: this.todoData.currentTodoItem.id, text: e.detail })),
      onTodoToggleUpdate: (e) => dispatch(toggleTodo(e.detail)),
      onTodoDelete: (e) => dispatch(deleteTodo(e.detail)),
    };

    dispatch(readTodo());
  }
  stateChanged(state) {
    this.selectedFilter = getSelectedFilter(state);
    this.todoData = getVisibleTodos(state.todo, this.selectedFilter.id);
  }
  render() {
    return html`
      <app-todo-list
        .todoData=${this.todoData}
        .events=${this.events}
      ></app-todo-list>
    `;
  }
}

customElements.define('todo-list-container', TodoListContainer);
