// templates/chota-angular-ngrx/src/containers/TodoFiltersContainer.ts
import { AsyncPipe } from '@angular/common';
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '../app/state/index';
import { getFilters } from '../app/state/filters/filters.selectors';
import { setVisibilityFilter } from '../app/state/filters/filters.actions';
import TodoFiltersComponent from '../ui/organisms/TodoFilters/TodoFilters.component';

@Component({
  selector: 'app-todo-filters-container',
  standalone: true,
  imports: [TodoFiltersComponent, AsyncPipe],
  template: `
    @if (filtersData$ | async; as filtersData) {
      <app-todo-filters
        [filtersData]="filtersData"
        [events]="events"
      ></app-todo-filters>
    }
  `,
})
export default class TodoFiltersContainerComponent {
  filtersData$ = this.store.select(getFilters);

  events = {
    onTodoFilterUpdate: (id: string) => {
      this.store.dispatch(setVisibilityFilter({ filter: id }));
    },
  };

  constructor(private store: Store<AppState>) {}
}

// templates/chota-wc-saga/src/containers/TodoFiltersContainer.js
import { LitElement, html } from 'lit-element';
import store, { useDispatch } from '../state';
import { connect } from 'pwa-helpers';

import "../ui/organisms/TodoFilters/app-todo-filters";

import { setVisibilityFilter } from "../state/filters/filters.action";


export default class TodoFiltersContainer extends connect(store)(LitElement) {
  static get properties() {
    return {
      filtersData: { type: Object },
      events: { type: Object }
    };
  }
  constructor() {
    super();
    const dispatch = useDispatch();
    this.events = {
      onTodoFilterUpdate: (e) => dispatch(setVisibilityFilter(e.detail)),
    };
  }
  stateChanged(state) {
    this.filtersData = state.filters;
  }
  render() {
    return html`
      <app-todo-filters
        .filtersData=${this.filtersData}
        .events=${this.events}
      ></app-todo-filters>
    `;
  }
}

customElements.define('todo-filters-container', TodoFiltersContainer);
