// templates/chota-vue-pinia/src/containers/SiteHeaderContainer.vue

<template>
  <SiteHeader :headerData="{ brandName: configData.config.name, theme: configData.config.theme }" :events="events" />
</template>

<script>
import { defineComponent } from 'vue';
import { useConfigStore } from '../state/config';
import SiteHeader from '../ui/organisms/SiteHeader/SiteHeader.component.vue'

export default defineComponent({
  components: {
    SiteHeader
  },
  props: [],
  setup() {
    const configData = useConfigStore();
    const events = {
      onThemeChangeClick: () => configData.updateConfig({ theme: configData.config.theme === "light" ? "dark" : "light" })
    };

    return {
      configData,
      events,
    }
  },
})
</script>

// templates/chota-react-zustand/src/containers/SiteHeaderContainer.jsx
import useStore from "../state";
import SiteHeader from "../ui/organisms/SiteHeader/SiteHeader.component";
export default function SiteHeaderContainer() {
  const configData = useStore((state) => state.config);
  const updateConfig = useStore((state) => state.updateConfig);
  const events = {
    onThemeChangeClick: () =>
      updateConfig({ theme: configData.theme === "light" ? "dark" : "light" }),
  };

  const headerData = { brandName: configData.name, theme: configData.theme };
  return (
    <SiteHeader
      headerData={headerData}
      events={events}
    />
  );
}
