// templates/chota-vue-pinia/src/containers/TodoFiltersContainer.vue
<template>
  <TodoFilters :filtersData="filtersData.filters" :events="events" />
</template>

<script>
import { defineComponent } from 'vue';
import { useFiltersStore } from '../state/filters';
import TodoFilters from '../ui/organisms/TodoFilters/TodoFilters.component.vue'

export default defineComponent({
  components: {
    TodoFilters
  },
  props: [],
  setup() {
    const filtersData = useFiltersStore();
    const events = {
      onTodoFilterUpdate: (id) => { console.log('id', id); filtersData.setVisibilityFilter(id); },
    };

    return {
      filtersData,
      events,
    }
  },
})
</script>

// templates/chota-react-zustand/src/containers/TodoFiltersContainer.jsx
import useStore from "../state";
import TodoFilters from "../ui/organisms/TodoFilters/TodoFilters.component";

export default function TodoFiltersContainer() {
  const filtersData = useStore((state) => state.filters);
  const setVisibilityFilter = useStore((state) => state.setVisibilityFilter);

  const events = {
    onTodoFilterUpdate: (id) => setVisibilityFilter(id),
  };

  return <TodoFilters filtersData={filtersData} events={events} />;
}
