// templates/chota-angular-ngrx/src/ui/atoms/TodoItem/TodoItem.component.ts
import { Component, Input, Output, EventEmitter, ViewEncapsulation } from '@angular/core';
import InputComponent from '../Input/Input.component';
import IconButtonComponent from '../IconButton/IconButton.component';

@Component({
  selector: 'app-todo-item',
  standalone: true,
  imports: [InputComponent, IconButtonComponent],
  templateUrl: './TodoItem.component.html',
  styleUrls: ['./TodoItem.style.css'],
  encapsulation: ViewEncapsulation.None,
})
export default class TodoItemComponent {
  @Input() id: number | null = null;
  @Input() text = '';
  @Input() completed = false;
  @Input() isDisabled = false;

  get checkboxId() {
    return `checkbox${this.id}`;
  }

  @Output() onToggleClick = new EventEmitter<any>();
  @Output() onEditClick = new EventEmitter<any>();
  @Output() onDeleteClick = new EventEmitter<any>();
}

<li
  [style.text-decoration]="completed ? 'line-through' : 'none'"
  class="todo-item"
>
  <label [attr.for]="checkboxId">
    <app-input
      [id]="checkboxId"
      name="checkbox"
      type="checkbox"
      [checked]="completed"
      (onChange)="onToggleClick.emit($event)"
    ></app-input>
    {{ text }}
    <span class="icon-buttons">
      <app-icon-button
        variant="clear"
        alt="edit"
        iconName="edit"
        size="16"
        (onClick)="onEditClick.emit($event)"
      ></app-icon-button>
      <app-icon-button
        variant="clear"
        alt="remove"
        iconName="trash-2"
        size="16"
        (onClick)="onDeleteClick.emit($event)"
      ></app-icon-button>
    </span>
  </label>
</li>

// templates/chota-wc-saga/src/ui/atoms/TodoItem/TodoItem.component.js
import { html } from "lit";
import style from "./TodoItem.style";

import useComputedStyles from "../../../utils/theme/hooks/useComputedStyles";
import emit from "../../../utils/events/emit";

import "../Input/app-input";
import "../IconButton/app-icon-button";

function TodoItem({
  onToggleClick,
  completed,
  text,
  id,
  onEditClick,
  onDeleteClick,
}) { 
  useComputedStyles(this, [style]);
  return html`
  <li
    style=${
      `text-decoration: ${completed ? "line-through" : "none"};`
    }
    class="todo-item"
  >
    <label htmlFor=${`checkbox${id}`}>
      <app-input
        id=${`checkbox${id}`}
        @onInput=${(e) => emit(this, "onToggleClick", e)}
        name="checkbox"
        .type=${`checkbox`}
        @onChange=${(e) => e.target.value}
        .checked=${completed}
      ></app-input>
        ${text}
      <span class="icon-buttons">
        <app-icon-button
          .variant=${`clear`}
          .alt=${`edit`}
          .iconName=${`edit`}
          .size=${`16`}
          @onClick=${(e) => emit(this, "onEditClick", e)}
        ></app-icon-button>
        <app-icon-button
          .variant=${`clear`}
          .alt=${`edit`}
          .iconName=${`trash-2`}
          .size=${`16`}
          @onClick=${(e) => emit(this, "onDeleteClick", e)}
        ></app-icon-button>
      </span>
    </label>
  </li>
  `;
}

export default TodoItem;
