// templates/chota-wc-saga/src/ui/organisms/TodoList/TodoList.component.js
import { html } from "lit";
import "../../atoms/Alert/app-alert";
import "../../molecules/AddTodoForm/app-add-todo-form";
import "../../molecules/TodoItems/app-todo-items";
import "../../skeletons/Skeleton/app-skeleton";

export default function TodoList({ todoData, events }) {
  const {
    onTodoCreate,
    onTodoEdit,
    onTodoUpdate,
    onTodoToggleUpdate,
    onTodoDelete,
  } = events;
  return html`
      ${todoData.error ? html`
        <app-alert
          .variant=${"error"}
          .show=${!!todoData.error}
          .message=${todoData.error}
        ></app-alert>
      ` : null}
      <app-add-todo-form
        .todoValue=${todoData.currentTodoItem.text || ""}
        @onTodoAdd=${onTodoCreate}
        @onTodoUpdate=${onTodoUpdate}
        .placeholder=${"Add your task"}
        .isLoading=${todoData.isActionLoading}
        .buttonInfo=${{
          label: todoData.currentTodoItem.text ? "Save" : "Add",
          variant: "primary",
        }} 
      ></app-add-todo-form>
      ${todoData.isContentLoading ? html`
          <br />
          <app-skeleton height="24px" ></app-skeleton>
          <br />
          <app-skeleton height="24px" ></app-skeleton>
          <br />
          <app-skeleton height="24px" ></app-skeleton>
      ` : html`
          <app-todo-items
            .todos=${todoData.todoItems || []}
            .isDisabled=${todoData.isActionLoading}
            @onToggleClick=${onTodoToggleUpdate}
            @onDeleteClick=${onTodoDelete}
            @onEditClick=${onTodoEdit}
          ></app-todo-items>
      `}
  `;
}

// templates/chota-angular-ngrx/src/ui/organisms/TodoList/TodoList.component.ts
import { Component, Input } from '@angular/core';
import AlertComponent from '../../atoms/Alert/Alert.component';
import AddTodoFormComponent from '../../molecules/AddTodoForm/AddTodoForm.component';
import TodoItemsComponent from '../../molecules/TodoItems/TodoItems.component';
import SkeletonComponent from '../../skeletons/Skeleton/Skeleton.component';
import { TodoState } from '../../../app/state/todo/todo.initial';

@Component({
  selector: 'app-todo-list',
  standalone: true,
  imports: [AlertComponent, AddTodoFormComponent, TodoItemsComponent, SkeletonComponent],
  templateUrl: './TodoList.component.html',
  styleUrls: ['./TodoList.style.css'],
})
export default class TodoListComponent {
  @Input() todoData: TodoState = {
    isLoading: false,
    isActionLoading: false,
    isContentLoading: false,
    error: '',
    todoItems: [],
    currentTodoItem: { id: null, text: '' },
  };

  @Input() events: {
    onTodoCreate: (text: string) => void;
    onTodoEdit: (todo: any) => void;
    onTodoUpdate: (text: string) => void;
    onTodoToggleUpdate: (todo: any) => void;
    onTodoDelete: (id: number) => void;
  } = {
    onTodoCreate: () => {},
    onTodoEdit: () => {},
    onTodoUpdate: () => {},
    onTodoToggleUpdate: () => {},
    onTodoDelete: () => {},
  };

  get buttonInfo() {
    return {
      label: this.todoData?.currentTodoItem?.text ? 'Save' : 'Add',
      variant: 'primary',
    };
  }
}


@if (todoData.error) {
  <app-alert
    variant="error"
    [show]="!!todoData.error"
    [message]="todoData.error"
  ></app-alert>
}
<app-add-todo-form
  [todoValue]="todoData.currentTodoItem.text || ''"
  (onTodoAdd)="events.onTodoCreate($event)"
  (onTodoUpdate)="events.onTodoUpdate($event)"
  placeholder="Add your task"
  [isLoading]="todoData.isActionLoading"
  [buttonInfo]="buttonInfo"
></app-add-todo-form>
@if (todoData.isContentLoading) {
  <br />
  <app-skeleton height="24px"></app-skeleton>
  <br />
  <app-skeleton height="24px"></app-skeleton>
  <br />
  <app-skeleton height="24px"></app-skeleton>
} @else {
  <app-todo-items
    [todos]="todoData.todoItems"
    [isDisabled]="todoData.isActionLoading"
    (onToggleClick)="events.onTodoToggleUpdate($event)"
    (onDeleteClick)="events.onTodoDelete($event)"
    (onEditClick)="events.onTodoEdit($event)"
  ></app-todo-items>
}
