// templates/chota-wc-saga/src/containers/SiteHeaderContainer.js
import { LitElement, html } from 'lit-element';
import store, { useDispatch } from '../state';
import { connect } from 'pwa-helpers';

import '../ui/organisms/SiteHeader/app-site-header';

import { updateConfig } from "../state/config/config.actions";


export default class SiteHeaderContainer extends connect(store)(LitElement) {
  static get properties() {
    return {
      headerData: { type: Object },
      events: { type: Object }
    };
  }
  constructor() {
    super();
    const dispatch = useDispatch();
    this.events = {
      onThemeChangeClick: () => dispatch(
        updateConfig({ theme: this.configData.theme === "light" ? "dark" : "light" })
      ),
    };
  }
  stateChanged(state) {
    const configData = state.config;
    this.configData = state.config;
    this.headerData = { brandName: configData.name, theme: configData.theme };
  }
  render() {
    return html`
      <app-site-header
        .headerData=${this.headerData}
        .events=${this.events}
      ></app-site-header>
    `;
  }
}

customElements.define('site-header-container', SiteHeaderContainer);

// templates/chota-angular-ngrx/src/containers/SiteHeaderContainer.ts
import { AsyncPipe } from '@angular/common';
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { map, take } from 'rxjs/operators';
import { AppState } from '../app/state/index';
import { getConfigState } from '../app/state/config/config.selectors';
import { updateConfig } from '../app/state/config/config.actions';
import SiteHeaderComponent from '../ui/organisms/SiteHeader/SiteHeader.component';

@Component({
  selector: 'app-site-header-container',
  standalone: true,
  imports: [SiteHeaderComponent, AsyncPipe],
  template: `
    @if (headerData$ | async; as headerData) {
      <app-site-header
        [headerData]="headerData"
        [events]="events"
      ></app-site-header>
    }
  `,
})
export default class SiteHeaderContainerComponent {
  headerData$ = this.store.select(getConfigState).pipe(
    map((config) => ({ brandName: config.name, theme: config.theme }))
  );

  events = {
    onThemeChangeClick: () => {
      this.headerData$.pipe(take(1)).subscribe((data) => {
        this.store.dispatch(
          updateConfig({ payload: { theme: data.theme === 'light' ? 'dark' : 'light' } })
        );
      });
    },
  };

  constructor(private store: Store<AppState>) {}
}
