// templates/chota-wc-saga/src/containers/TodoListContainer.js
import { LitElement, html } from 'lit-element';
import store, { useDispatch } from '../state';
import { connect } from 'pwa-helpers';

import "../ui/organisms/TodoFilters/app-todo-filters";

import {
  createTodo,
  deleteTodo,
  editTodo,
  readTodo,
  toggleTodo,
  updateTodo,
} from "../state/todo/todo.actions";

import { getSelectedFilter } from "../state/filters/filters.selectors";
import { getVisibleTodos } from "../state/todo/todo.selectors";

import "../ui/organisms/TodoList/app-todo-list";

export default class TodoListContainer extends connect(store)(LitElement) {
  static get properties() {
    return {
      todoData: { type: Object },
      selectedFilter: { type: Object },
      events: { type: Object }
    };
  }
  constructor() {
    super();
    const dispatch = useDispatch();
    this.events = {
      onTodoCreate: (e) => dispatch(createTodo(e.detail)),
      onTodoEdit: (e) => dispatch(editTodo(e.detail)),
      onTodoUpdate: (e) =>
        dispatch(updateTodo({ id: this.todoData.currentTodoItem.id, text: e.detail })),
      onTodoToggleUpdate: (e) => dispatch(toggleTodo(e.detail)),
      onTodoDelete: (e) => dispatch(deleteTodo(e.detail)),
    };

    dispatch(readTodo());
  }
  stateChanged(state) {
    this.selectedFilter = getSelectedFilter(state);
    this.todoData = getVisibleTodos(state.todo, this.selectedFilter.id);
  }
  render() {
    return html`
      <app-todo-list
        .todoData=${this.todoData}
        .events=${this.events}
      ></app-todo-list>
    `;
  }
}

customElements.define('todo-list-container', TodoListContainer);

// templates/chota-angular-ngrx/src/containers/TodoListContainer.ts
import { AsyncPipe } from '@angular/common';
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';
import { take } from 'rxjs/operators';
import { AppState } from '../app/state/index';
import { getVisibleTodos, getTodoState } from '../app/state/todo/todo.selectors';
import { Todo } from '../app/state/todo/todo.model';
import {
  addTodoRequest,
  editTodo,
  updateTodoRequest,
  toggleTodo,
  deleteTodoRequest,
} from '../app/state/todo/todo.actions';
import TodoListComponent from '../ui/organisms/TodoList/TodoList.component';

@Component({
  selector: 'app-todo-list-container',
  standalone: true,
  imports: [TodoListComponent, AsyncPipe],
  template: `
    @if (todoData$ | async; as todoData) {
      <app-todo-list
        [todoData]="todoData"
        [events]="events"
      ></app-todo-list>
    }
  `,
})
export default class TodoListContainerComponent {
  todoData$ = this.store.select(getVisibleTodos);

  events = {
    onTodoCreate: (text: string) => {
      this.store.dispatch(addTodoRequest({ text }));
    },
    onTodoEdit: (todo: Todo) => {
      this.store.dispatch(editTodo({ id: todo.id, text: todo.text }));
    },
    onTodoUpdate: (text: string) => {
      this.store.select(getTodoState).pipe(take(1)).subscribe((state) => {
        const { id } = state.currentTodoItem;
        if (id !== null) {
          this.store.dispatch(updateTodoRequest({ id, text }));
        }
      });
    },
    onTodoToggleUpdate: (todo: Todo) => {
      this.store.dispatch(toggleTodo({ id: todo.id }));
    },
    onTodoDelete: (id: number) => {
      this.store.dispatch(deleteTodoRequest({ id }));
    },
  };

  constructor(private store: Store<AppState>) {}
}
